import { ThemeConfig } from 'antd';
import colors from '../scss/palette.module.scss';

export const components: ThemeConfig['components'] = {
  Menu: {
    itemActiveBg: '#e6f4ff',
    itemSelectedBg: '#e6f4ff',
    itemSelectedColor: '#1677ff',
    activeBarWidth: 3,
    itemBorderRadius: 0,
    itemMarginInline: 0,
  },
  Switch: {
    trackMinWidth: 30,
    trackHeight: 16,
    handleSize: 12,
    colorPrimary: colors['switch-primary-bg'],
    colorPrimaryHover: colors['switch-primary-hover'],
  },
  Button: {
    colorPrimary: colors['btn-primary-bg'],
    colorPrimaryHover: colors['btn-primary-hover'],
    colorPrimaryActive: colors['btn-primary-active'],
    borderRadius: 15,
    primaryShadow: 'none',
    colorBgContainerDisabled: colors['btn-primary-bg-disabled'],
    borderColorDisabled: colors['btn-border-disabled'],
    colorTextDisabled: colors['text-disabled'],
    colorLink: colors['btn-primary-bg'],
    colorLinkHover: colors['btn-primary-hover'],
    colorLinkActive: colors['btn-primary-active'],
    controlHeightLG: 52,
    controlHeight: 32,
    controlHeightSM: 32,
    borderRadiusLG: 15,
    borderRadiusSM: 15,
    fontSizeLG: 14,
    defaultBorderColor: colors['page-bg'],
    colorText: colors['btn-secondary-text'],
    defaultHoverBg: colors['btn-secondary-hover'],
    defaultHoverBorderColor: colors['btn-secondary-hover'],
    defaultActiveBg: colors['btn-secondary-active'],
  },
  Pagination: {
    itemActiveBg: colors['pagination-active-bg'],
    colorText: colors['text-dark'],
    colorPrimary: colors['pagination-active-text'],
    colorPrimaryHover: 'none',
    colorPrimaryBorder: 'none',
  },
  Dropdown: {
    colorText: colors['primary-color'],
    controlItemBgHover: colors['dropdown-item-hover'],
  },
  Breadcrumb: {
    itemColor: colors['breadcrumb-item'],
    linkColor: colors['breadcrumb-item'],
    lastItemColor: colors['breadcrumb-last-item'],
    linkHoverColor: colors['breadcrumb-item-hover'],
    separatorColor: colors['breadcrumb-item'],
    colorBgTextHover: 'transparent',
    fontSize: 12,
    separatorMargin: 5,
  },
  Input: {
    controlHeight: 40,
    inputFontSize: 14,
    colorBorder: colors['input-border'],
    colorText: colors['text-dark'],
    hoverBorderColor: colors['input-hover'],
    activeBorderColor: colors['input-active'],
    colorBgContainerDisabled: colors['input-bg-disabled'],
    colorTextDisabled: colors['text-disabled'],
    activeShadow: 'none',
    colorErrorBorderHover: colors['input-border-error'],
  },
  InputNumber: {
    controlHeight: 40,
    inputFontSize: 14,
    colorBorder: colors['input-border'],
    colorText: colors['text-dark'],
    activeShadow: 'none',
    errorActiveShadow: 'none',
    hoverBorderColor: colors['input-hover'],
    colorBgContainerDisabled: colors['input-bg-disabled'],
    activeBorderColor: colors['input-active'],
    colorErrorBorderHover: colors['input-border-error'],
    colorTextDisabled: colors['text-disabled'],
  },
  Select: {
    controlHeight: 40,
    fontSizeLG: 14,
    colorText: colors['text-dark'],
    colorBorder: colors['input-border'],
    colorPrimaryHover: colors['text-disabled'],
    colorBgContainerDisabled: colors['input-bg-disabled'],
    colorIcon: 'red',
    colorBorderSecondary: '#5597F8',
  },
  Radio: {
    radioSize: 18,
    dotSize: 8,
    lineWidth: 2,
    colorPrimary: colors['btn-primary-bg'],
    colorPrimaryHover: colors['btn-primary-hover'],
    colorBorder: colors['btn-primary-bg'],
    colorBgContainerDisabled: 'white',
    colorTextBase: colors['primary-color'],
    colorTextDisabled: colors['text-disabled'],
    dotColorDisabled: colors['checkbox-bg-disabled'],
    borderRadiusLG: 5,
    fontSizeLG: 14,
  },
  DatePicker: {
    colorBorder: colors['input-border'],
    colorBgContainerDisabled: colors['input-bg-disabled'],
  },
  Checkbox: {
    controlInteractiveSize: 20,
    colorPrimary: colors['btn-primary-bg'],
    colorPrimaryHover: colors['btn-primary-hover'],
    colorBorder: colors['text-disabled'],
    colorBgContainerDisabled: colors['checkbox-bg-disabled'],
    colorTextDisabled: colors['text-disabled'],
  },
  Notification: {
    colorText: 'var(--color-black)',
    colorTextHeading: 'var(--color-black)',
    borderRadiusLG: 7,
  },
  Table: {
    headerBg: colors['table-header-bg'],
    rowSelectedBg: colors['table-row-selected-bg'],
    rowSelectedHoverBg: colors['table-row-selected-hover-bg'],
  },
  Calendar: {
    colorPrimary: colors['calendar-primary-color'],
    controlHeightSM: 32,
    borderRadiusSM: 50,
  },
  Collapse: {
    headerPadding: '0 4px 0 16px',
  },
};
